Export gateway url/token as env vars
scaleway/serverless-gateway pull request #21
Opened 2023-03-31 15:33 UTC by redanrd

## Summary

**_What's changed?_**
This add commands to make in order to get gateway's base url and a valid token. The readme instruct users to export these them into environment variables.
 
**_Why do we need this?_**
Ease user experience and demoing.

## Checklist

- [x] I have reviewed this myself
- [x] There is a unit test covering every change in this PR
- [x] I have updated the relevant documentation

2023-04-03 14:40 UTC, Shillaker requested changes

2023-04-03 14:40 UTC, Shillaker commented on README.md
>  curl -X POST http://<your container domain name>/scw \
Can we use the new target here, e.g.

```suggestion
export GATEWAY_URL=$(make get-gateway-endpoint)
export GATEWAY_TOKEN=$(make get-gateway-token)

curl -X POST ${GATEWAY_URL}/scw \
```

2023-04-03 14:40 UTC, Shillaker commented on README.md
> +             -H 'X-Auth-Token: <generated_key>' \
```suggestion
             -H 'X-Auth-Token: ${GATEWAY_TOKEN}' \
```

2023-04-04 08:32 UTC, cyclimse approved these changes

2023-04-04 09:16 UTC, Shillaker approved these changes

2023-04-04 09:52 UTC, merged